/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.*;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @BeforeEach
    void init()  throws IOException{
        String data="";
        data = new String(Files.readAllBytes(Paths.get("C:\\Users\\Ahmad\\asac\\401Course\\quotes\\app\\src\\main\\resources\\recentquotes.json")));
        Gson gson= new Gson();
        Quote AllquotesArray [] = gson.fromJson(data,Quote [].class);
    }
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void quoteTextTest() throws IOException {
        String data="";
        data = new String(Files.readAllBytes(Paths.get("C:\\Users\\Ahmad\\asac\\401Course\\quotes\\app\\src\\main\\resources\\recentquotes.json")));
        Gson gson= new Gson();
        Quote AllquotesArray [] = gson.fromJson(data,Quote [].class);
        assertEquals("If you work really hard, and you're kind, amazing things will happen", AllquotesArray[51].getText());
    }

    @Test
    public void QuoteAuthorTest() throws IOException {
        String data="";
        data = new String(Files.readAllBytes(Paths.get("C:\\Users\\Ahmad\\asac\\401Course\\quotes\\app\\src\\main\\resources\\recentquotes.json")));
        Gson gson= new Gson();
        Quote AllquotesArray [] = gson.fromJson(data,Quote [].class);
        assertEquals("Conan O'Brien", AllquotesArray[51].getAuthor());
    }

}
