/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import java.io.*;
import java.nio.file.*;
import com. google. gson. *;
import java.util.Random;

import java.util.ArrayList;
import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
//        File myJsonFile = new File("C:\\Users\\Ahmad\\asac\\401Course\\quotes\\app\\src\\main\\resources\\recentquotes.json");
//        BufferedReader jsonContent= new BufferedReader(new FileReader(myJsonFile));
        String data="";
        data = new String(Files.readAllBytes(Paths.get("C:\\Users\\Ahmad\\asac\\401Course\\quotes\\app\\src\\main\\resources\\recentquotes.json")));
        Gson gson= new Gson();
        /*
        solution with change the Quote type
        ArrayList <Quote> AllquotesArray = new ArrayList<Quote>();

        AllquotesArray = gson.fromJson(data,Quote.class);

         */

        Quote AllquotesArray [] = gson.fromJson(data,Quote [].class);
        Random rand = new Random();
        int randomNum= rand.nextInt(AllquotesArray.length);

        System.out.println(randomNum);
        System.out.println(AllquotesArray[randomNum].getText());
        System.out.println(AllquotesArray[randomNum].getAuthor());





    }

}
